baseURL: 'https://swsoyee.vercel.app/'
languageCode: en-us
defaultContentLanguage: en-us
title: Infinity Loop
theme: hugo-tranquilpeak-theme
googleAnalytics: 'UA-131217026-1'
disqusShortname: 'infinityloop-netlify-app'
paginate: 7
canonifyurls: true
permalinks:
  post: '/:year/:month/:slug/'
taxonomies:
  tag: tags
  category: categories
  archive: archives
author:
  name: Su Wei
  bio: Opportunity favors only the prepared mind.
  job: Front-end Engineer
  location: Tokyo, Japan
  picture: https://z3.ax1x.com/2021/02/12/yrPJ4s.jpg
  twitter: "swsoyee"
menu:
  main:
    - weight: 1
      identifier: home
      name: Home
      pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      url: /
    - weight: 2
      identifier: categories
      name: Categories
      pre: <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      url: /categories
    - weight: 3
      identifier: tags
      name: Tags
      pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      url: /tags
    - weight: 4
      identifier: archives
      name: Archives
      pre: <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      url: /archives
    - weight: 5
      identifier: about
      name: About
      pre: <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      url: /#about
  links:
    - weight: 1
      identifier: github
      name: GitHub
      pre: <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      url: 'https://github.com/swsoyee'
    - weight: 2
      identifier: twitter
      name: Twitter
      pre: <i class="sidebar-button-icon fa fa-lg fa-twitter"></i>
      url: 'https://twitter.com/swsoyee'
  misc:
    - weight: 1
      identifier: rss
      name: RSS
      pre: <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      url: /index.xml
params:
  dateFormat: '2006 January 2'
  syntaxHighlighter: highlight.js
  clearReading: false
  math: true
  hierarchicalCategories: true
  description: Infinity Loop's blog
  sidebarBehavior: 2
  coverImage: https://z3.ax1x.com/2021/02/12/yrPfKK.jpg
  imageGallery: true
  thumbnailImage: true
  thumbnailImagePosition: bottom
  autoThumbnailImage: true
  sharingOptions:
    - name: Facebook
      icon: fa-facebook-official
      url: 'https://www.facebook.com/sharer/sharer.php?u=%s'
    - name: Twitter
      icon: fa-twitter
      url: 'https://twitter.com/intent/tweet?text=%s'
    - name: Google+
      icon: fa-google-plus
      url: 'https://plus.google.com/share?url=%s'
  header:
    rightLink:
      class: ''
      icon: ''
      url: /#about
  footer:
    copyright: "<a href=\"https://github.com/swsoyee\">Su Wei</a>"
