name: build-test

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: build example
        run: |
          cd exampleSite
          mkdir themes
          ln -s ../.. themes/fuji
          hugo
